/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX_1_aliases.h"
#include "RX_1.h"
#include "LED_Driver_Gear.h"
#include "TX_1_aliases.h"
#include "TX_1.h"
#include "Com_1_aliases.h"
#include "Com_1.h"
#include "Seg_1_aliases.h"
#include "Tx_En_aliases.h"
#include "Tx_En.h"
#include "Seg_aliases.h"
#include "Com_aliases.h"
#include "LED_Driver_LRBWS.h"
#include "CAN.h"
#include "LED_Driver_Gear_ClkInternal.h"
#include "LED_Driver_Gear_Seg_Driver_L.h"
#include "LED_Driver_Gear_Com_Driver.h"
#include "LED_Driver_Gear_DMA_Com_dma.h"
#include "LED_Driver_Gear_DMA_Seg_dma.h"
#include "LED_Driver_LRBWS_ClkInternal.h"
#include "LED_Driver_LRBWS_Seg_Driver_L.h"
#include "LED_Driver_LRBWS_Com_Driver.h"
#include "LED_Driver_LRBWS_DMA_Com_dma.h"
#include "LED_Driver_LRBWS_Seg_Driver_M.h"
#include "LED_Driver_LRBWS_Seg_Driver_H.h"
#include "LED_Driver_LRBWS_DMA_Seg_dma.h"
#include "LED_Driver_LRBWS_DMA_BC_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

